# Example: Mass Balances and Linear Algebra

## Learning Objectives

After studying this notebook, completing the activities, and asking questions in class, you should be able to:
* Solve a system of linear equations by creating a model and implementing it in matrix form in python.
* Calculate results and interpret the meaning of the results.

In [1]:
# Import libraries
import numpy as np
import scipy.linalg as la

## Atomic Species (Mass) Balance
**Reference:** Example 4.7-1 in *Elementary Principles of Chemical Process Engineering*, Third Edition, Felder and Rousseau (2005)

Methane is burned with air in a continuous steady-state combustion reactor to yield a mixture of carbon monoxide, carbon dioxide, and water. The reactions taking place are:

CH$_4$ + $\frac{3}{2}$ O$_2$ $\rightarrow$ CO + 2 H$_2$O

CH$_4$ + 2 O$_2$ $\rightarrow$ CO$_2$ + 2 H$_2$O

The feed to the reactor contains 7.80 mole% CH$_4$, 19.4% O$_2$, and 72.8% N$_2$. The percentage conversion of methane is 90.0%, and the gas leaving the reactor contains 8 mol CO$_2$/mol CO. What is the molar composition of the product stream?

**Do the following using [this handout:](https://raw.githubusercontent.com/ndcbe/data-and-computing/main/extras/atomic-mass-balance-activity.docx)**
1. Draw a picture
2. Propose a mathematical model using atomic species balances
3. Perform degree of freedom analysis
4. Convert your model to a linear system
5. Solve with Python
6. Print your answer to the screen with a reasonable number of significant digits

In [2]:
# Add your solution here




A = 
 [[ 0  0  0  0  0  1]
 [ 1  0  0  0  0  0]
 [ 0  8 -1  0  0  0]
 [ 1  1  1  0  0  0]
 [ 4  0  0  2  0  0]
 [ 0  1  2  1  2  0]] 

b = 
 [72.8   0.78  0.    7.8  31.2  38.8 ] 

The molar flows are:
n1 = 0.780 mol
n2 = 0.780 mol
n3 = 6.240 mol
n4 = 14.040 mol
n5 = 5.750 mol
n6 = 72.800 mol

Condition Number of A: 26.693350866495237

pl:
 [[ 0.          0.          0.         -0.          0.          1.        ]
 [ 0.25        0.          0.          0.48571429  1.          0.        ]
 [ 0.          1.          0.          0.          0.          0.        ]
 [ 0.25        0.125       0.52941176  1.          0.          0.        ]
 [ 1.          0.          0.          0.          0.          0.        ]
 [ 0.          0.125       1.          0.          0.          0.        ]]

u:
 [[ 4.          0.          0.          2.          0.          0.        ]
 [ 0.          8.         -1.          0.          0.          0.        ]
 [ 0.          0.          2.125       1.          

array([ 0.78,  0.78,  6.24, 14.04,  5.75, 72.8 ])