# Linear Algebra Review and SciPy Basics

**Reference:** Section 2.2 Vectors and Matrices in *Nonlinear Programming: Concepts, Algorithms, and Applications to Chemical Processes* by L. T. Bielger (2010).

**Recommended Links**
* [NumPy Documentation - Main Page](https://docs.scipy.org/doc/numpy-1.15.0/reference/)
* [SciPy Documentation - Main Page](https://docs.scipy.org/doc/scipy-1.1.0/reference/)
* [SciPy Linear Algebra - Tutorial](https://docs.scipy.org/doc/scipy-1.1.0/reference/tutorial/linalg.html)
* [SciPy Linear Algebra - API](https://docs.scipy.org/doc/scipy-1.1.0/reference/linalg.html)
* [SciPy Lecture Notes](http://www.scipy-lectures.org/) (Especially 1.1 - 1.6 for everyone and 2.1 - 2.2 for advanced users)

Tip: We will mostly use SciPy for linear algebra. (It has more sophisticated capabilities than NumPy.) We will use NumPy if/when SciPy does not offer a specific command.

## Learning Objectives

After studying this notebook, completing the activities, and asking questions in class, you should be able to:
* Understand matrix operations on paper and in python.
* Explain what a determinant is and how to calculate it; know its properties.
* Calculate the rank of a matrix by hand and in python.
* Know the conditions for a matrix to have an inverse, and how to calculate its inverse.
* Understand how to solve linear systems in various ways, including LU decompostion.
* Be familiar with the invertible matrix theorem.
* Calculate and interpret eigenvalues.
* Perform singular value decomposition and interpret the results.
* Calculate vector and matrix norms.

In [2]:
# Load required Python libraries.
import matplotlib.pyplot as plt
import numpy as np
from scipy import linalg

## Notation for CBE 40499/60499 and Bielger (2010)
The following is somewhat standard notation in scientific computing and data science literature:
* Scalars (constants and variables): Lowercase Greek letters (more common), lowercase non-bold Roman letters (especially if dictated by science or engineering context/domain norms)

CBE 40499/60499: We will sometimes use

* Vectors - Lower case bold Roman letter, lowercase bold Greek letters (if dictated by science or engineering domain norms)
* Matrices - Upper case bold Roman letters, uppercase bold Greek letters (if dictated by science and engineering domain norms)

The notation for lectures will (hopefully) be obvious from context. I sometimes use Greek letters for constants and Roman letters for variables... unless the Greek letters have engineering or scientific meaning.


## Matrix Operations

In this section we will introduce properties of matrices with code examples following each property.

## Property #1

Multiplying two matrices $A$ $\in$ $\mathbb{R}^{n \times m}$ and $B$ $\in$ $\mathbb{R}^{m \times p}$ leads to the product $C \in$ $\mathbb{R}^{n \times p}$ with elements $ \mathbf{\{C\}_{ij}}$ = $\sum_{k=1}^m  \mathbf{\{A\}_{ik}}  \mathbf{\{B\}_{kj}}$. This operation is defined only if the number of columns in $A$ and rows of $B$ is the same.

<div class="admonition seealso"> 
<p class="title"><b>Home Activity</b></p>
 The code below demonstrates matrix multiplication.  Before running the code below, what is the dimension of A*B?
</div>

In [3]:
# Generate random matrices
n = 2
m = 3

Ao = np.random.rand(n,m)
Bo = np.random.rand(m,n)

print("Ao = ")
print(Ao)
print("\nBo = ")
print(Bo)

# Calculate Ao*Bo using Python
print("\nAo*Bo =")
print(Ao.dot(Bo))

Ao = 
[[0.76486904 0.04561386 0.23738663]
 [0.85825884 0.06187272 0.7838835 ]]

Bo = 
[[0.47388783 0.84976499]
 [0.85191129 0.23476259]
 [0.52742191 0.75555075]]

Ao*Bo =
[[0.526524   0.84002501]
 [0.87286582 1.33610749]]


Another way of multiplying matrices is by using the "@" symbol.  See an example below with Ao and Bo.

In [4]:
# calculate Ao*Bo using @
print("Ao*Bo =")
print(Ao@Bo)

Ao*Bo =
[[0.526524   0.84002501]
 [0.87286582 1.33610749]]


## Property #2

The *transpose* of $A$ $\in$ $\mathbb{R}^{n \times m}$ is $A^T$ $\in$ $\mathbb{R}^{m \times n}$ with the rows and columns of A interchanged, i.e.$ \mathbf{\{A^T\}_{ij}} =  \mathbf{\{A\}_{ji}}$.

<div class="admonition seealso"> 
<p class="title"><b>Home Activity</b></p>
 Calculate $A_o^{T}$
</div>

In [3]:
# Transpose
# Add your solution here

transpose(Ao) = 
 [[0.53920696 0.7755139 ]
 [0.96955407 0.6767133 ]
 [0.90975543 0.4823789 ]] 



## Property #3

A *symmetric* matrix $A$ $\in$ $\mathbb{R}^{n \times n}$ satisfies $A = A^T$.

## Property #4

A *diagonal* matrix $A$ $\in$ $\mathbb{R}^{n \times n}$ has nonzero elements only on the diagonal, i.e., $ \mathbf{\{A\}_{ij}} = 0, i \neq j$.

<div class="admonition seealso">
<p class="title"><b>Home Activity</b></p>
 Create a random $3 \times 3$ square matrix and check if it is symmetric by comparing it to its transpose.</div>

In [4]:
# Create square matrix and compare with transpose
# Add your solution here

Square matrix:
 [[0.60448601 0.78627006 0.89597215]
 [0.97879566 0.63284257 0.5811153 ]
 [0.32982237 0.1736945  0.17994575]]
Transpose of square matrix:
 [[0.60448601 0.97879566 0.32982237]
 [0.78627006 0.63284257 0.1736945 ]
 [0.89597215 0.5811153  0.17994575]]


## Property #5

The *identity* matrix $I \in \mathbb{R}^{n \times n}$ is defined as 

$$  \mathbf{\{I\}_{ij}}=   \left\{
\begin{array}{ll}
      1 \text{ if } i = j, \\
      0 \text{ otherwise.} \\
\end{array} 
\right.  $$

<div class="admonition seealso">
<p class="title"><b>Home Activity</b></p>
 Create a 3x3 identity matrix.</div>

In [5]:
# Identity matrix
# Add your solution here

I = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



## Determinant

A *determinant* is a scalar associated to a square matrix, i.e., det($A$) for $A$ $\in$ $\mathbb{R}^{n \times n}$, and can be defined recursively by det($A$) = $\sum_i (-1)^{i+j} \mathbf{\{A\}_{ij}} \bar{A}_{ij}$ for any column $j$, or det($A$) = $\sum_j (-1)^{i+j} \mathbf{\{A\}_{ij}}\bar{A}_{ij}$ for any row $i$, where $\bar{A}_{ij}$ is the determinant of an ($n$-1)-order matrix with row $i$ and column $j$ removed.

We will now manipulate the following matrices to demonstrate properties for the determinant.

In [6]:
# Generate random matrices
nd = 2

A = np.random.rand(nd,nd)
B = np.random.rand(nd,nd)

print("A = ")
print(A)
print("\nB = ")
print(B)

A = 
[[0.13785899 0.28113758]
 [0.59708216 0.31166715]]

B = 
[[0.5493066  0.04429576]
 [0.2740967  0.54012404]]


## Property #1

det($AB$) = det($A$)det($B$)

<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Calculate the determinante of $AB$ and prove it is equal to the product of the determinants of $A$ and $B$.</div>

In [7]:
# Property 1
# Add your solution here

det(A*B) =  -0.035539486674939995
det(A)*det(B) =  -0.035539486674939995


## Property #2

det($A$) = det($A^T$)

<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Calculate the determinant of $A$ and of $A^T$ and prove they are equal.</div>

In [8]:
# Property 2
# Add your solution here

det(A) =  -0.12489611574912461
det(A^T) =  -0.12489611574912461


## Property #3

For an $n \times n$ matrix with scalar $\alpha$, det($\alpha A$) = $\alpha^n$det($A$)

<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Calculate the determinant of $\alpha A$ and calculate $\alpha$det($A$) and prove they are equal. Let $\alpha$ = 4.</div>

In [9]:
# Property 3
# Add your solution here

det(alpha*A) =  -1.9983378519859938
alpha*det(A) =  -0.49958446299649845


## Property #4

For an identity matrix $I$, det($I$) = 1.

<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Create a $3 \times 3$ identity matrix and calculate the determinant.</div>

In [10]:
# Property 4
# Add your solution here

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
det(I) =  1.0


## Calculating $3 \times 3$ Determinant by Hand

Below is an example from *Linear Algebra and Its Applications* by David C. Lay, 3rd edition that shows how to calculate a determinant by hand.

<div class="admonition seealso"> 
<p class="title"><b>Home Activity</b></p>
 Walk through the following example that calculates a $3 \times 3$ determinant by hand.
</div>

For $ n \geq 2$, the **determinant** of an $n \times n$ matrix $A$ = [$a_{ij}$] is the sum of $n$ terms of the form $\pm a_{1j}$ det$A_{1j}$, with plus and minus signs alternating, where the entries $a_{11},a_{12},...,a_{1n}$ are from the first row of $A$.  In symbols, 

det$A$ = $a_{11}$det$A_{11}-a_{12}$det$A_{12}+...+(-1)^{1+n}a_{1n}$det$A_{1n}$
    
= $\sum_{j=1}^n (-1)^{1+j}a_{1j}\text{det}A_{1j}$

**Example:** Compute the determinate of the matrix $A$ = 
$ \begin{bmatrix}
1 & 5 & 0\\
2 & 4 & -1\\
0 & -2 & 0
\end{bmatrix}$

**Solution:** Compute det($A$) = $a_{11}$det$A_{11}-a_{12}$det$A_{12}+a_{13}$det$A_{13}$:

det$A$ = $1\cdot$det$\begin{bmatrix} 4 & -1\\ -2 & 0 \end{bmatrix}$ - $5\cdot$det$\begin{bmatrix} 2 & -1\\ 0 & 0 \end{bmatrix}$ + $0\cdot$det$\begin{bmatrix} 2 & 4\\ 0 & -2 \end{bmatrix}$

$= 1(0-2) - 5(0-0) + 0(-4-0)$ 

$= -2$

## Rank


## Matrix Rank Definition


**Rerference:** Section 2.2 of *Nonlinear Programming: Concepts, Algorithms, and Applications to Chemical Processes*, L. Biegler (2010)

* The rank of a matrix $r(A)$ is the order of the largest submatrix in $A$ that has a nonzero determinant.
* A matrix $A$ $\in$ $\mathbb{R}^{n \times m}$ has full row (column) rank if none of the row (column) vectors can be written as a linear combination of the other row (column) vectors.  The rank of such a matrix is $r(A)$ = min($n,m$).
* A matrix that does not have full rank is *rank deficient*.

## Practice Activities


<div class="admonition seealso"> 
<p class="title"><b>Home Activity</b></p>
 Predict the rank of $A_1^T$, $B_1^T$, $C_1$, and $D_1$.
</div>

In [11]:
# Generate random matrices
n = 2
m = 3

A_1 = np.random.rand(n,m)
B_1 = np.random.rand(m,n)
C_1 = np.array([[0, 2, 0], [1, 2, 3], [0, 4, 0]])
D_1 = np.array([[3, 2, 4], [1, 2, 4], [0, 6, 5]])

print("A_1 = ")
print(A_1)
print("\nB_1 = ")
print(B_1)
print("\nC_1 = ")
print(C_1)
print("\nD_1 = ")
print(D_1)

A_1 = 
[[0.70268875 0.55298945 0.56890907]
 [0.46535378 0.01446308 0.23871531]]

B_1 = 
[[0.04058466 0.17097646]
 [0.81132754 0.88760492]
 [0.75098347 0.33147803]]

C_1 = 
[[0 2 0]
 [1 2 3]
 [0 4 0]]

D_1 = 
[[3 2 4]
 [1 2 4]
 [0 6 5]]


**My answers:**

Rank of A_1T: 

Rank of B_1T:

Rank of C_1:

Rank of D_1:

<div class="admonition seealso"> 
<p class="title"><b>Home Activity</b></p>
 Check the rank of these four matrices by calculating each with np.linalg.matrix_rank( ).  Were you correct?
</div>

In [12]:
# Calculate ranks
# Add your solution here

rank(A_1T) =  2 

rank(B_1T) =  2 

rank(C_1) =  2 

rank(D_1) =  3 



## Inverse


## Inverse of a Matrix Defnition

**Rerference:** Section 2.2 of *Nonlinear Programming: Concepts, Algorithms, and Applications to Chemical Processes*, L. Biegler (2010)

* If the matrix $A$ $\in$ $\mathbb{R}^{n \times n}$ is nonsingular, i.e., has full rank, then an *inverse* $A^{-1}$ exists that satisfies $AA^{-1} = A^{-1}A = I$.
* The linear system $Ax = b$ with nonsingular $A$ $\in$ $\mathbb{R}^{n \times m}$, $x \in \mathbb{R}^n$, and $b \in \mathbb{R}^n$, has a unique solution $x = A^{-1}b$.
* det($A^{-1}$) = $\frac{1}{\text{det}(A)}$.
* A matrix $Q \in \mathbb{R}^{n \times n}$ with the property $Q^{-1} = Q^T$ is called an *orthogonal matrix*.

## Practice Activities

<div class="admonition seealso">
<p class="title"><b>Home Activity</b></p>
 Calculate the inverse of $A_o$ and verity that $A_o^{-1} A_o = I$. 
</div>

In [13]:
# Generate A_0
n = 3
m = 3
A_0 = np.random.rand(n,m)
print("A_0 = ")
print(A_0)

# Calculate inverse
# Add your solution here

# Verification
# Add your solution here

A_0 = 
[[0.39383547 0.73470596 0.34702043]
 [0.97487    0.383215   0.69163964]
 [0.24203568 0.51795548 0.4197325 ]]
A_0 inverse = 
 [[ 1.75705999  1.14506957 -3.33953463]
 [ 2.15221581 -0.72381285 -0.58667173]
 [-3.66905871  0.23289869  5.03214873]]
[[ 1.00000000e+00 -3.34057763e-18 -1.65304858e-16]
 [ 1.50464795e-16  1.00000000e+00 -1.32648796e-16]
 [-6.57375717e-17 -7.47308550e-18  1.00000000e+00]]


What do you notice about the matrix produced from $A_o^{-1} A_o$?  Why do you think this happens?

<div class="admonition seealso">
<p class="title"><b>Home Activity</b></p>
 Verify that det($A_0^{-1}$) = $\frac{1}{\text{det}(A_0)}$.
</div>

In [14]:
# Verification
# Add your solution here

det(A_0inv) =  -8.901429960994944
1/det(A_0) =  -8.90142996099494


<div class="admonition seealso">
    <p class="title"><b>Home Activity</b></p>
 Is $Q$ an orthogonal matrix? Yes, no, or need more information?
</div>

In [15]:
# Create Q
theta = 0.2
Q = np.array([(np.cos(theta), -np.sin(theta)),(np.sin(theta),np.cos(theta))])
print("Q = ")
print(Q)

# Verification
# Add your solution here

Q = 
[[ 0.98006658 -0.19866933]
 [ 0.19866933  0.98006658]]
Qinv = 
 [[ 0.98006658  0.19866933]
 [-0.19866933  0.98006658]]
Q^T = 
 [[ 0.98006658  0.19866933]
 [-0.19866933  0.98006658]]


## Solving Linear Systems
Consider the linear system $A_1 x = b_1$

In [16]:
A1 = np.array([(4,3),(6,3)])
b1 = np.array([1,0])
print("A1 = \n",A1)
print("\nb1 = \n",b1)

A1 = 
 [[4 3]
 [6 3]]

b1 = 
 [1 0]


## Explicit Inverse

Calculate $x$ by explicitly using $A_l^{-1}$. Hint: Use linalg.inv( ).

In [17]:
# Calculate inverse
# Add your solution here

# Now calculate and print x
# Add your solution here

Ainv = 
 [[-0.5         0.5       ]
 [ 1.         -0.66666667]] 

x = 
 [[-0.5  0. ]
 [ 1.  -0. ]]


## LU Decomposition


In [18]:
# Create test linear systems for the following examples
A = np.random.rand(4,4)
print("A = \n",A,"\n")

b = np.random.rand(4,1)
print("b = \n",b,"\n")

A = 
 [[0.19532048 0.80213917 0.0896026  0.7891849 ]
 [0.51242877 0.60202691 0.04460208 0.99673738]
 [0.66205227 0.74912751 0.64881305 0.5885614 ]
 [0.65721088 0.25512709 0.60784324 0.00341296]] 

b = 
 [[0.81894293]
 [0.61659727]
 [0.35223602]
 [0.82622819]] 



<div class="admonition seealso">
    <p class="title"><b>Home Activity</b></p>
 Follow along with the LU decomposition on $A$. What structures do the $P$, $L$, and $U$ matrices have? 
</div>

In [19]:
# Perform LU decomposition
(P, L, U) = linalg.lu(A)

# Permutation matrix
print("P = \n",P)

# Lower diagonal matrix
print("L = \n",L)

# Upper diagonal matrix
print("U = \n",U)

# Verify result
print("P*L*U = \n",P.dot(L.dot(U)),"\n")

P = 
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
L = 
 [[ 1.          0.          0.          0.        ]
 [ 0.29502275  1.          0.          0.        ]
 [ 0.77400047  0.03820467  1.          0.        ]
 [ 0.99268729 -0.84064268  0.26849349  1.        ]]
U = 
 [[ 0.66205227  0.74912751  0.64881305  0.5885614 ]
 [ 0.          0.58112951 -0.10181202  0.6155459 ]
 [ 0.          0.         -0.45368983  0.51767385]
 [ 0.          0.          0.         -0.20238236]]
P*L*U = 
 [[0.19532048 0.80213917 0.0896026  0.7891849 ]
 [0.51242877 0.60202691 0.04460208 0.99673738]
 [0.66205227 0.74912751 0.64881305 0.5885614 ]
 [0.65721088 0.25512709 0.60784324 0.00341296]] 



## Is P orthogonal?

In [20]:
print("inv(P) = \n",linalg.inv(P),"\n")

print("transpose(P) = \n",P.T,"\n")

print("P.T*P = \n",np.matmul(P.T,P),"\n")

inv(P) = 
 [[-0.  0.  1. -0.]
 [ 1.  0.  0. -0.]
 [ 0.  1.  0. -0.]
 [ 0.  0.  0.  1.]] 

transpose(P) = 
 [[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]] 

P.T*P = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 



**Yes!** We see that $P^T = P^{-1}$ and $P^T \cdot P = I$.

## MATLAB

Defines LU decomposition as follows:

$$ P \cdot A = L \cdot U$$

Consider 

$$A \cdot x=b$$

Using MATLAB LU definition

$$P\cdot A = L\cdot U$$

$$P^T \cdot P \cdot A = P^T \cdot L \cdot U$$

$$A = P^T \cdot L \cdot U$$

Substitute into linear system:

$$P^T \cdot L \cdot U \cdot x = b$$

$$ L \cdot U \cdot x = P \cdot b$$

Let $y = U \cdot x$ and substitute.

Step 1. Solve $L \cdot y = P \cdot b$ for $y$

Step 2. Solve $U \cdot x = y$ for $x$

In [21]:
# Calculate Pb
Pb = P.dot(b)
print("P*b = \n",Pb,"\n")

# Step 1
yLU = linalg.solve(L,Pb)
print("yLU = \n",yLU,"\n")

# Step 2
xLU = linalg.solve(U,yLU)
print("xLU = \n",xLU,"\n")

P*b = 
 [[0.61659727]
 [0.35223602]
 [0.81894293]
 [0.82622819]] 

yLU = 
 [[0.61659727]
 [0.1703258 ]
 [0.33518912]
 [0.26732696]] 

xLU = 
 [[ 2.83715187]
 [ 1.29873196]
 [-2.24599425]
 [-1.32090047]] 



## SciPy

Defines LU decomposition as:

$$ A = P \cdot L \cdot U $$

Consider 

$$A \cdot x=b$$

SciPy LU definition

$$A = P \cdot L\cdot U$$

Substitute into linear system:

$$P \cdot L \cdot U \cdot x = b$$
$$P^T \cdot P \cdot L \cdot U \cdot x = P^T \cdot b$$
$$L \cdot U \cdot x = P^T \cdot b$$

Let $y = U \cdot x$ and substitute.

Step 1. Solve $L \cdot y = P^T \cdot b$ for $y$

Step 2. Solve $U \cdot x = y$ for $x$

In [22]:
## LU decomposition algorithm.
Pb = (P.T).dot(b)
print("P.T*b = \n",Pb,"\n")

# Step 1
yLU = linalg.solve(L,Pb)
print("yLU = \n",yLU,"\n")

# Step 2
xLU = linalg.solve(U,yLU)
print("xLU = \n",xLU,"\n")

P.T*b = 
 [[0.35223602]
 [0.81894293]
 [0.61659727]
 [0.82622819]] 

yLU = 
 [[0.35223602]
 [0.71502529]
 [0.31664912]
 [0.99263052]] 

xLU = 
 [[ 5.03790151]
 [ 5.32285245]
 [-6.29438561]
 [-4.90472838]] 



**What is the difference?** A transpose.


## Verify our answer with `linalg.solve`

Solve the linear system using linalg.solve

In [23]:
x = linalg.solve(A,b)
print("x = \n",x)

x = 
 [[ 5.03790151]
 [ 5.32285245]
 [-6.29438561]
 [-4.90472838]]


## Invertable Matrix Theorem
**Refernce:** *Linear Algebra and Its Applications* by David C. Lay, 3rd edition

*Hold on to your hats folks!*

Let $A$ be a square $n \times n$ identity matrix. Then the following statements are equivalent. That is, for a given $A$, the statements are either all true or all false.


a. $A$ is an invertible matrix.

b. $A$ is row equivalent to the $n \times n$ identity matrix.

c. $A$ has $n$ pivot positions.

d. The equation $Ax = 0$ has only the trivial solution.

e. The columns of $A$ form a linearly independent set.

f. The linear transformation $x\longmapsto Ax$ is one-to-one.

g. The equation $Ax = b$ has at least one solution for each $b$ in $\mathbb{R}^n$.

h. The columns of $A$ span $\mathbb{R}^n$.

i. The linear transformation $x\longmapsto Ax$ maps $\mathbb{R}^n$ onto $\mathbb{R}^n$.

j. There is an $n \times n$ matrix $C$ such that $CA = I$.

k. There is an $n \times n$ matrix $D$ such that $AD = I$.

l. $A^T$ is an invertible matrix.

**Let $A$ be an $n \times n$ matrix. Then the following statements are each equivalent to the statement that $A$ is an invertible matrix.**

m. The columns of $A$ form a basis of $\mathbb{R}^n$.

n. Col$A$ = $\mathbb{R}^n$

o. dim Col$A$ = $N$

p. rank $A$ = $N$

q. Nul$A$ = $\{0\}$

r. dim Nul$A$ = $0$

**Let $A$ be an $n \times n$ matrix. Then $A$ is invertible if and only if:**

s. The number 0 is *not* an eigenvalue of $A$.

t. The determinant of $A$ is *not* zero.

**Let $A$ be an $n \times n$ matrix. Then the following statements are each equivalent to the statement that $A$ is an invertible matrix.**

u. (Col$A$)$^\perp$ = $\{0\}$.

v. (Nul$A$)$^\perp$ = $\mathbb{R}^n$.

w. Row$A$ = $\mathbb{R}^n$.

x. $A$ has $n$ nonzero singular values.

## Eigenvectors and Eigenvalues


## Eigenvalues/Eigenvectors Definition

* For a square matrix $A \in \mathbb{R}^{n\times n}$, the *eigenvalue* $\lambda$ and the corresponding *eigenvector* $v \neq 0$ satisfy $Av = \lambda v$.
* Because $(A-\lambda I)v = 0$, $(A-\lambda I)$ is singular, and we can define a characteristic $n$th degree polynomial given by det$(A-\lambda I)$ = $0$ to find the $n$ eigenvalues.
* det$(A)$ = $\prod_{i=1}^n\lambda_i$.
* Eigenvalues of symmetric matrices are always real. Moreover, by collecting eigenvectors and eigenvalues, a symmetric matrix $A \in \mathbb{R}^{n \times n}$ can be represented by $A = V\wedge V^T$, where $V$ is the orthogonal matrix of eigenvectors, $\mathbf{V = [v_1,v_2,...,v_n]}$, and $\wedge$ is a diagonal matrix of eigenvalues with $ \mathbf{\{\wedge\}_{ii} = \lambda_i}$.
* Nonsymmetric matrices can have complex eigenvalues. Also, eigenvalues are not defined for nonsquare matrices. Instead, *singular values* $\sigma_i \geq 0$, $i = 1,...,m,$ are often useful to characterize $A \in \mathbb{R}^{n \times m}$ with $m \leq n$. These are derived from the eigenvalues of $(A^TA)$ with $\sigma_i = [\lambda_i(A^TA)]^{\frac{1}{2}}$.
* Consider the matrix $A \in \mathbb{R}^{n \times m}$ with all real eigenvalues. Such matrices can be further classified as follows:
    - Matrices with $\lambda_i > 0, i = 1,n,$ are said to be *positive definite*; i.e., $y^TAy > 0$ for all $y \neq 0$.
    - Matrices with $\lambda_i < 0, i = 1,n,$ are said to be *negative definite*; i.e., $y^TAy < 0$ for all $y \neq 0$.
    - Matrices with $\lambda_i \geq 0, i = 1,n,$ are said to be *positive semidefinite*; i.e., $y^TAy \geq 0$ for all $y \neq 0$.
    - Matrices with $\lambda_i \leq 0, i = 1,n,$ are said to be *negative semidefinite*; i.e., $y^TAy \leq 0$ for all $y \neq 0$.
    - Matrices with both positive and negative eigenvalues are *indefinite*.
    - A matrix with $\lambda_i = 0$, for some $i$, is *singular*.

## Practice Activities

In [24]:
# Create matrix for activities
Ae = np.array([(0, -4, -6), (-1, 0, -3), (1, 2, 5)])
print("Ae = \n",Ae)

Ae = 
 [[ 0 -4 -6]
 [-1  0 -3]
 [ 1  2  5]]


<div class="admonition seealso">
<p class="title"><b>Home Activity</b></p>
 Do you expect the above matrix to have negative eigenvalues?
</div>

**Choose:** Yes/No/Cannot tell from inspection.

**Justification:**

<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Calculate the eigenvalues and corresponding eigenvectors.
</div>

In [25]:
# Calculations
# Add your solution here

Matrix = 
 [[ 0 -4 -6]
 [-1  0 -3]
 [ 1  2  5]] 

Eigenvalues =  [1.+0.j 2.+0.j 2.+0.j] 

Eigenvectors = 
 [[-0.81649658 -0.0111458   0.90265832]
 [-0.40824829 -0.8302799   0.1523847 ]
 [ 0.40824829  0.5572352  -0.40247591]] 



<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Based on your calculations above, is this matrix i) positive definite, ii) positive semi definite, iii) negative definite, iv) negative semi definite, v) indefinite, or vi) cannot say without additional calculations? Write a sentence to justify your answer.
</div>

**Answer:**

<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Calculate the determinate using only the eigenvalues.
    </div>

In [26]:
# Determinate calculation
# Add your solution here

Det =  (3.9999999999999973+0j)


<a id='SVD_cell'></a>
## Singular Value Decomposition
Refer to [this notebook](../04/LU-Decomposition.ipynb) for notes on singular value decomposition.

Remember, SVD can be thought of as another type of matrix factorization.  We can represent an $m \times n$ matrix as $A = U\cdot \sum \cdot V^T$.

<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Calculate the singular value decomposition of $A_d$ and $B_d$.
    </div>

In [27]:
# Generate matrices
n = 2
m = 3
A_d = np.random.rand(n,m)
B_d = np.random.rand(m,n)
print("A_d = ")
print(A_d)
print("\nB_d = ")
print(B_d)

# Add your solution here

A_d = 
[[0.4485645  0.94396271 0.90630531]
 [0.65550619 0.17113477 0.79723747]]

B_d = 
[[0.70939505 0.75872279]
 [0.68693568 0.29736702]
 [0.9430575  0.19822265]]

SVD for A_d... 

U = 
 [[-0.81497106 -0.57950166]
 [-0.57950166  0.81497106]] 

S = 
 [1.65873224 0.50678934] 

V = 
 [[-0.44939984 -0.52357768 -0.72381365]
 [ 0.54120061 -0.80419622  0.24570374]
 [-0.7107332  -0.28130917  0.64476622]] 


SVD for B_d... 

U = 
 [[-0.64065863  0.73692217  0.21564379]
 [-0.48291242 -0.1683662  -0.85933021]
 [-0.59695236 -0.65467438  0.46373413]] 

S = 
 [1.54265526 0.43367475] 

V = 
 [[-0.87457662 -0.48488734]
 [-0.48488734  0.87457662]] 



<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 What is the rank of each matrix? (from inspecting singular values?)
    </div>

**Answer:**

## Vector and Matrix Norms

**Rerference:** Section 2.2 of *Nonlinear Programming: Concepts, Algorithms, and Applications to Chemical Processes*, L. Biegler (2010)

## Vector Norm Properties

* A *vector norm* $\parallel \cdot \parallel$ is a measure of the length of a vector and it maps from $\mathbb{R}^n$ to a nonegative real that has the following properties:

    1) $\parallel x\parallel = 0 \Rightarrow x=0$ for $x \in \mathbb{R}^n$,

    2) $\parallel \alpha x\parallel = |\alpha | \parallel x\parallel$ for all $x \in \mathbb{R}^n$, $\alpha \in \mathbb{R}^n$,

    3) $\parallel x+y\parallel \; \leq \; \parallel x\parallel + \parallel y\parallel$ for all $x,y \in \mathbb{R}^n$.


## *P*-norm Properties

* The *p*-norm is defined by $\parallel x\parallel _p = (\sum_{i=1}^n |x_i|^p)^{\frac{1}{p}}$, where $p \geq 1$. Examples and properties include:

    1) $p=1, \parallel x\parallel_1 = \sum_{i=1}^n |x_i|$, the 1-norm,

    2) $p=2, \parallel x\parallel_2 = (\sum_{i=1}^n x_i^2)^{\frac{1}{2}}$, the Euclidean norm,

    3) $p=\infty , \parallel x\parallel_{\infty}$ = max$_i |x_i|$, the max-norm,

    4) $|x^Ty| \leq \; \parallel x\parallel_p \parallel y\parallel_q$ for 1/$p$ + 1/$q$ = 1 and all $x, y \in \mathbb{R}^n$.

Also, for $x \in \mathbb{R}^n$ each norm can be bounded above and below by a multiple of any of the other norms.

<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Verify the vector norm properties hold for the p-2 norm using $x$ and $y$. Hint: linalg.norm( )
    </div>

In [28]:
# Create vectors for following activites
x = np.random.rand(3,1)
print("x = \n",x)

y = np.random.rand(3,1)
print("y = \n",y)

x = 
 [[0.22147533]
 [0.95260672]
 [0.21153669]]
y = 
 [[0.75695275]
 [0.33364788]
 [0.28968871]]


In [29]:
# Verification of p-norm property #2
# Add your solution here

# Verification of p-norm property #4
# Add your solution here

||x||_2 =  1.0006291272585606
x solution =  1.0006291272585606
||y||_2 =  0.8764804148148981
y solution =  0.8764804148148981

|x^Ty| =  0.5467613583758554
||x_2|| ||y_2|| =  0.8770318325354527


## Additional Matrix Norms

* For $A \in \mathbb{R}^{n \times m}$, the induced matrix norms are defined by vector norms: $\parallel A\parallel$ = max$_{X \neq 0} \frac{\parallel Ax \parallel}{\parallel x \parallel}$ for any *p*-norm. It is therefore consistent with vector norms and satisfies $\parallel A\parallel \; \parallel x\parallel \; \geq \; \parallel Ax\parallel$. Examples include:

    1) $\parallel A\parallel_1$ = max$_j(\sum_{i=1}^n |\{A\}_{ij}|)$ (max column sum of $A$)

    2) $\parallel A\parallel_{\infty}$ = max$_i(\sum_{j=1}^m |\{A\}_{ij}|)$ (max row sum of $A$)

    3) $\parallel A\parallel_2$ = largest singular value of $A$.


<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Calculate $||A_l||_1$, $||A_l||_{\infty}$ and $||A_l||_2$ using both the rules given above and SciPy
    </div>

In [30]:
# Create A_1 matrix for following activities
n = 2
m = 3
A_1 = np.random.rand(n,m)
print(A_1)

[[0.5969     0.26938739 0.14392162]
 [0.90718853 0.3676809  0.00275836]]


In [31]:
# Calculate ||A_l||_1
# Add your solution here

# Calculate ||A_l||_2
# Add your solution here


Computing ||A||_1 ...
Vector of column sums:  [1.50408853 0.63706829 0.14667998]
||A||_1 using rules above:  1.504088526958932
||A||_1 using scipy:   1.504088526958932

Computing ||A||_inf ...
Vector of row sums: 
 [[1.01020901]
 [1.27762779]]
||A||_inf using rules above:  1.2776277908438523
||A||_inf using scipy:  1.2776277908438523

Computing ||A||_2 ...
||A||_2 using rules above:  0.9071885314790465
||A||_inf using scipy:  1.180438147895785


## Frobenius Norm

* The Frobenius norm $\parallel A\parallel_F = (\sum_i \sum_j ( \mathbf{\{A\}_{ij})^2)^{\frac{1}{2}}}$ is not consistent with a vector norm but has some useful properties. This norm as well as the induced norms satisfy $\parallel AB\parallel \; \leq \parallel A\parallel \; \parallel B\parallel$ for any two compatible matrices $A$ and $B$. In addition, the induced and Frobenius matrix norms can be bounded above and below by a multiple of any of the other matrix norms.

## Condition Number


For more information on condition number, reference [this notebook](../04/LU-Decomposition.ipynb).
* The *condition number* is defined by $\kappa (A) = \parallel A\parallel \; \parallel A^{-1} \parallel$. Using the induced 2-norm the condition number is given by $\frac{\sigma_{\text{max}}}{\sigma_{\text{min}}}$. If $A$ is a symmetric matrix, then this is equivalent to using the eigenvalues of $A$ with $\frac{\lambda_{\text{max}}}{\lambda_{\text{min}}}$.

Refernce the [SVD cell from above](#SVD_cell) to answer the following two activities.

<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Estimate the condition number of $A_d$ using the above rule.
    </div>

In [32]:
# Condition number using rule
# Add your solution here

Condition Number:  1.6587322424578173 / 0.5067893389326414 = 3.273021184603655


<div class="admonition note"> 
<p class="title"><b>Class Activity</b></p>
 Calculate the condition number of $A_d$ using np.linalg.cond( ).
    </div>

In [33]:
# Condition number using numpy
# Add your solution here

Condition number:  3.273021184603655
