# Linear Algebra Review and SciPy Basics

Screenshots from Section **2.2 Vectors and Matrices** in Biegler (2010)

**Recommended Links**
* [NumPy Documentation - Main Page](https://docs.scipy.org/doc/numpy-1.15.0/reference/)
* [SciPy Documentation - Main Page](https://docs.scipy.org/doc/scipy-1.1.0/reference/)
* [SciPy Linear Algebra - Tutorial](https://docs.scipy.org/doc/scipy-1.1.0/reference/tutorial/linalg.html)
* [SciPy Linear Algebra - API](https://docs.scipy.org/doc/scipy-1.1.0/reference/linalg.html)
* [SciPy Lecture Notes](http://www.scipy-lectures.org/) (Especially 1.1 - 1.6 for everyone and 2.1 - 2.2 for advanced users)

Tip: We will mostly use SciPy for linear algebra. (It has more sophisticated capabilities than NumPy.) We will use NumPy if/when SciPy does not offer a specific command.

In [1]:
# Load required Python libraries.
import matplotlib.pyplot as plt
import numpy as np
from scipy import linalg

## Notation (for textbook)
* Scalar constants and variables - Greek letters
* Vectors - Lower case Roman letters
* Matrices - Upper case Roman letters

The notation for lectures will (hopefully) be obvious from context. I sometimes use Greek letters for constants and Roman letters for variables... unless the Greek letters have engineering or scientific meaning.


## Matrix Operations

*Section **2.2 Vectors and Matrices** in Biegler (2010)*

In this section we will introduce properties of matrices with code examples following each property.

### Property #1:

Multiplying two matrices $A$ $\in$ $\mathbb{R}^{n \times m}$ and $B$ $\in$ $\mathbb{R}^{m \times p}$ leads to the product $C \in$ $\mathbb{R}^{n \times p}$ with elements $\{C\}_{ij}$ = $\sum_{k=1}^m \{A\}_{ik}\{B\}_{kj}$. This operation is defined only if the number of columns in $A$ and rows of $B$ is the same.

<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;"> 
<b>Home Activity</b>: The code below demonstrates matrix multiplication.  Before running the code below, what is the dimension of A*B?
</div>

In [4]:
# Generate random matrices
n = 2
m = 3

Ao = np.random.rand(n,m)
Bo = np.random.rand(m,n)

print("Ao = ")
print(Ao)
print("\nBo = ")
print(Bo)

# Calculate A*B using Python
print("\nAo*Bo =")
print(Ao.dot(Bo))

Ao = 
[[0.79460559 0.92852087 0.93083124]
 [0.90967038 0.16844344 0.63759139]]

Bo = 
[[0.22484908 0.38813638]
 [0.52860634 0.29418532]
 [0.21365975 0.35361078]]

Ao*Bo =
[[0.86836952 0.91072451]
 [0.42980643 0.62808895]]


### Property #2:

The *transpose* of $A$ $\in$ $\mathbb{R}^{n \times m}$ is $A^T$ $\in$ $\mathbb{R}^{m \times n}$ with the rows and columns of A interchanged, i.e.$\{A^T\}_{ij} = \{A\}_{ji}$.

<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;"> 
<b>Home Activity</b>: Calculate $A_o^{T}$
</div>

In [5]:
# Transpose
### BEGIN SOLUTION
print("transpose(Ao) = \n",Ao.transpose(),"\n")
### END SOLUTION

transpose(Ao) = 
 [[0.79460559 0.90967038]
 [0.92852087 0.16844344]
 [0.93083124 0.63759139]] 



### Property #3:

A *symmetric* matrix $A$ $\in$ $\mathbb{R}^{n \times n}$ satisfies $A = A^T$.

### Property #4:

A *diagonal* matrix $A$ $\in$ $\mathbb{R}^{n \times n}$ has nonzero elements only on the diagonal, i.e., $\{A\}_{ij} = 0, i \neq j$.

<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;">
<b>Home Activity</b>: Create a random $3 \times 3$ square matrix and check if it is symmetric by comparing it to its transpose.</div>

In [6]:
# Create square matrix and compare with transpose
### BEGIN SOLUTION
square = np.random.rand(3,3)
print("Square matrix:\n",square)
squareT = square.transpose()
print("Transpose of square matrix:\n", squareT)
### END SOLUTION

Square matrix:
 [[0.34058144 0.6323501  0.34221605]
 [0.06285987 0.5263325  0.24616663]
 [0.6781021  0.51967506 0.70846924]]
Transpose of square matrix:
 [[0.34058144 0.06285987 0.6781021 ]
 [0.6323501  0.5263325  0.51967506]
 [0.34221605 0.24616663 0.70846924]]


### Property #5:

The *identity* matrix $I \in \mathbb{R}^{n \times n}$ is defined as 
$$ \{I\}_{ij}=   \left\{
\begin{array}{ll}
      1 \text{ if } i = j, \\
      0 \text{ otherwise.} \\
\end{array} 
\right.  $$

<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;">
<b>Home Activity</b>: Create a 3x3 identity matrix.</div>

In [7]:
# Identity matrix
### BEGIN SOLUTION
print("I = \n",np.identity(3),"\n")
### END SOLUTION

I = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



## Determinant

*Section **2.2 Vectors and Matrices** in Biegler (2010)*

A *determinant* is a scalar associated to a square matrix, i.e., det($A$) for $A$ $\in$ $\mathbb{R}^{n \times n}$, and can be defined recursively by det($A$) = $\sum_i (-1)^{i+j}\{A\}_{ij}\bar{A}_{ij}$ for any column $j$, or det($A$) = $\sum_j (-1)^{i+j}\{A\}_{ij}\bar{A}_{ij}$ for any row $i$, where $\bar{A}_{ij}$ is the determinant of an ($n$-1)-order matrix with row $i$ and column $j$ removed.

We will now manipulate the following matrices to demonstrate properties for the determinant.

In [8]:
# Generate random matrices
nd = 2

A = np.random.rand(nd,nd)
B = np.random.rand(nd,nd)

print("A = ")
print(A)
print("\nB = ")
print(B)

A = 
[[0.30795044 0.32545939]
 [0.5654349  0.21466289]]

B = 
[[0.86620794 0.06143444]
 [0.51003603 0.12429083]]


The following properties are taken from Section **2.2 Vectors and Matrices** in Biegler (2010).

### Property #1: 

det($AB$) = det($A$)det($B$)

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Calculate the determinante of $AB$ and prove it is equal to the product of the determinants of $A$ and $B$.</div>

In [9]:
# Property 1
### BEGIN SOLUTION
print("det(A*B) = ",linalg.det(A.dot(B)))
print("det(A)*det(B) = ",linalg.det(A)*linalg.det(B))
### END SOLUTION

det(A*B) =  -0.009000632323405821
det(A)*det(B) =  -0.00900063232340583


### Property #2:

det($A$) = det($A^T$)

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Calculate the determinant of $A$ and of $A^T$ and prove they are equal.</div>

In [10]:
# Property 2
### BEGIN SOLUTION
print("det(A) = ", linalg.det(A))
print("det(A^T) = ", linalg.det(A.transpose()))
### END SOLUTION

det(A) =  -0.11792056875458154
det(A^T) =  -0.11792056875458154


### Property #3:

For an $n \times n$ matrix with scalar $\alpha$, det($\alpha A$) = $\alpha^n$det($A$)

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Calculate the determinant of $\alpha A$ and calculate $\alpha$det($A$) and prove they are equal. Let $\alpha$ = 4.</div>

In [11]:
# Property 3
### BEGIN SOLUTION
alpha = 4
print("det(alpha*A) = ", linalg.det(alpha*A))
print("alpha*det(A) = ", alpha*(linalg.det(A)))
### END SOLUTION

det(alpha*A) =  -1.8867291000733046
alpha*det(A) =  -0.47168227501832616


### Property #4:

For an identity matrix $I$, det($I$) = 1.

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Create a $3 \times 3$ identity matrix and calculate the determinant.</div>

In [12]:
# Property 4
### BEGIN SOLUTION
I = np.identity(3)
print(I)
print("det(I) = ", linalg.det(I))
### END SOLUTION

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
det(I) =  1.0


### Calculating $3 \times 3$ Determinant by Hand

Below is an example from *Linear Algebra and Its Applications* by David C. Lay, 3rd edition that shows how to calculate a determinant by hand.

<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;"> 
<b>Home Activity</b>: Walk through the following example that calculates a $3 \times 3$ determinant by hand.
</div>

For $ n \geq 2$, the **determinant** of an $n \times n$ matrix $A$ = [$a_{ij}$] is the sum of $n$ terms of the form $\pm a_{1j}$ det$A_{1j}$, with plus and minus signs alternating, where the entries $a_{11},a_{12},...,a_{1n}$ are from the first row of $A$.  In symbols, 

det$A$ = $a_{11}$det$A_{11}-a_{12}$det$A_{12}+...+(-1)^{1+n}a_{1n}$det$A_{1n}$
    
= $\sum_{j=1}^n (-1)^{1+j}a_{1j}\text{det}A_{1j}$

**Example:** Compute the determinate of the matrix $A$ = 
$\begin{bmatrix}
1 & 5 & 0\\
2 & 4 & -1\\
0 & -2 & 0
\end{bmatrix}$

**Solution:** Compute det($A$) = $a_{11}$det$A_{11}-a_{12}$det$A_{12}+a_{13}$det$A_{13}$:

det$A$ = $1\cdot$det$\begin{bmatrix} 4 & -1\\ -2 & 0 \end{bmatrix}$ - $5\cdot$det$\begin{bmatrix} 2 & -1\\ 0 & 0 \end{bmatrix}$ + $0\cdot$det$\begin{bmatrix} 2 & 4\\ 0 & -2 \end{bmatrix}$

$= 1(0-2) - 5(0-0) + 0(-4-0)$ 

$= -2$

## Rank


### Matrix Rank Definition


*Section **2.2 Vectors and Matrices** in Biegler (2010):*

* The rank of a matrix $r(A)$ is the order of the largest submatrix in $A$ that has a nonzero determinant.
* A matrix $A$ $\in$ $\mathbb{R}^{n \times m}$ has full row (column) rank if none of the row (column) vectors can be written as a linear combination of the other row (column) vectors.  The rank of such a matrix is $r(A)$ = min($n,m$).
* A matrix that does not have full rank is *rank deficient*.

### Practice Activities


<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;"> 
<b>Home Activity</b>: Predict the rank of $A_1^T$, $B_1^T$, $C_1$, and $D_1$.
</div>

In [16]:
# Generate random matrices
n = 2
m = 3

A_1 = np.random.rand(n,m)
B_1 = np.random.rand(m,n)
C_1 = np.array([[0, 2, 0], [1, 2, 3], [0, 4, 0]])
D_1 = np.array([[3, 2, 4], [1, 2, 4], [0, 6, 5]])

print("A_1 = ")
print(A_1)
print("\nB_1 = ")
print(B_1)
print("\nC_1 = ")
print(C_1)
print("\nD_1 = ")
print(D_1)

A_1 = 
[[0.10607203 0.87456671 0.51571556]
 [0.81183314 0.8439832  0.56909252]]

B_1 = 
[[0.42274669 0.66382384]
 [0.1719959  0.55386967]
 [0.81941494 0.36101201]]

C_1 = 
[[0 2 0]
 [1 2 3]
 [0 4 0]]

D_1 = 
[[3 2 4]
 [1 2 4]
 [0 6 5]]


**My answers:**

Rank of A_1T: 

Rank of B_1T:

Rank of C_1:

Rank of D_1:

<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;"> 
<b>Home Activity</b>: Check the rank of these four matrices by calculating each with np.linalg.matrix_rank( ).  Were you correct?
</div>

In [21]:
# Calculate ranks
### BEGIN SOLUTION
print("rank(A_1T) = ",np.linalg.matrix_rank(A_1.transpose()),"\n")
print("rank(B_1T) = ",np.linalg.matrix_rank(B_1.transpose()),"\n")
print("rank(C_1) = ",np.linalg.matrix_rank(C_1),"\n")
print("rank(D_1) = ",np.linalg.matrix_rank(D_1),"\n")
### END SOLUTION

rank(A_1T) =  2 

rank(B_1T) =  2 

rank(C_1) =  2 

rank(D_1) =  3 



## Inverse


### Inverse of a Matrix Defnition

*Section **2.2 Vectors and Matrices** in Biegler (2010)*

* If the matrix $A$ $\in$ $\mathbb{R}^{n \times n}$ is nonsingular, i.e., has full rank, then an *inverse* $A^{-1}$ exists that satisfies $AA^{-1} = A^{-1}A = I$.
* The linear system $Ax = b$ with nonsingular $A$ $\in$ $\mathbb{R}^{n \times m}$, $x \in \mathbb{R}^n$, and $b \in \mathbb{R}^n$, has a unique solution $x = A^{-1}b$.
* det($A^{-1}$) = $\frac{1}{\text{det}(A)}$.
* A matrix $Q \in \mathbb{R}^{n \times n}$ with the property $Q^{-1} = Q^T$ is called an *orthogonal matrix*.

### Practice Activities

<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;">
<b>Home Activity</b>: Calculate the inverse of $A_o$ and verity that $A_o^{-1} A_o = I$. 
</div>

In [65]:
# Generate A_0
n = 3
m = 3
A_0 = np.random.rand(n,m)
print("A_0 = ")
print(A_0)

# Calculate inverse
### BEGIN SOLUTION
A_0inv = np.linalg.inv(A_0)
print("A_0 inverse = \n", A_0inv)
### END SOLUTION

# Verification
### BEGIN SOLUTION
print(np.dot(A_0,A_0inv))
### END SOLUTION

A_0 = 
[[0.20185623 0.82280402 0.05232525]
 [0.02416247 0.23282261 0.70891661]
 [0.85693341 0.36796077 0.5526938 ]]
A_0 inverse = 
 [[-0.29228677 -0.96306742  1.26295694]
 [ 1.31386944  0.14755534 -0.31365102]
 [-0.42153921  1.39496783  0.05996318]]
[[ 1.00000000e+00 -9.93835444e-18  1.16639856e-17]
 [ 3.36802192e-17  1.00000000e+00 -1.24396576e-17]
 [ 1.46794872e-18  1.36472343e-17  1.00000000e+00]]


What do you notice about the matrix produced from $A_o^{-1} A_o$?  Why do you think this happens?

<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;">
<b>Home Activity</b>: Verify that det($A_0^{-1}$) = $\frac{1}{\text{det}(A_0)}$.
</div>

In [38]:
# Verification
### BEGIN SOLUTION
print("det(A_0inv) = ", linalg.det(A_0inv))
print("1/det(A_0) = ", 1/(linalg.det(A_0)))
### END SOLUTION

det(A_0inv) =  2.5710654690380665
1/det(A_0) =  2.571065469038067


<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;">
    <b>Home Activity</b>: Is $Q$ an orthogonal matrix? Yes, no, or need more information?
</div>

In [66]:
# Create Q
theta = 0.2
Q = np.array([(np.cos(theta), -np.sin(theta)),(np.sin(theta),np.cos(theta))])
print("Q = ")
print(Q)

# Verification
### BEGIN SOLUTION
print("Qinv = \n", linalg.inv(Q))
print("Q^T = \n", Q.transpose())
### END SOLUTION

Q = 
[[ 0.98006658 -0.19866933]
 [ 0.19866933  0.98006658]]
Qinv = 
 [[ 0.98006658  0.19866933]
 [-0.19866933  0.98006658]]
Q^T = 
 [[ 0.98006658  0.19866933]
 [-0.19866933  0.98006658]]


## Solving Linear Systems
Consider the linear system $A_1 x = b_1$

In [45]:
A1 = np.array([(4,3),(6,3)])
b1 = np.array([1,0])
print("A1 = \n",A1)
print("\nb1 = \n",b1)

A1 = 
 [[4 3]
 [6 3]]

b1 = 
 [1 0]


### Explicit Inverse

Calculate $x$ by explicitly using $A_l^{-1}$. Hint: Use linalg.inv().

In [47]:
# Calculate inverse
### BEGIN SOLUTION
Ainv = linalg.inv(A1)
print("Ainv = \n",Ainv,"\n")
### END SOLUTION

# Now calculate and print x
### BEGIN SOLUTION
x = Ainv*b1
print("x = \n",x)
### END SOLUTION

Ainv = 
 [[-0.5         0.5       ]
 [ 1.         -0.66666667]] 

x = 
 [[-0.5  0. ]
 [ 1.  -0. ]]


### LU Decomposition


In [49]:
# Create test linear systems for the following examples
A = np.random.rand(4,4)
print("A = \n",A,"\n")

b = np.random.rand(4,1)
print("b = \n",b,"\n")

A = 
 [[0.28599695 0.6807093  0.51865375 0.92604119]
 [0.10143027 0.53784679 0.55736184 0.78038639]
 [0.83656605 0.92077333 0.75609823 0.94869306]
 [0.4589657  0.60116199 0.55318533 0.46565042]] 

b = 
 [[0.04938299]
 [0.80236214]
 [0.22804181]
 [0.00301726]] 



<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;">
    <b>Home Activity</b>: Follow along with the LU decomposition on $A$. What structures do the $P$, $L$, and $U$ matrices have? 
</div>

In [50]:
# Perform LU decomposition
(P, L, U) = linalg.lu(A)

# Permutation matrix
print("P = \n",P)

# Lower diagonal matrix
print("L = \n",L)

# Upper diagonal matrix
print("U = \n",U)

# Verify result
print("P*L*U = \n",P.dot(L.dot(U)),"\n")

P = 
 [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
L = 
 [[ 1.          0.          0.          0.        ]
 [ 0.12124598  1.          0.          0.        ]
 [ 0.34187014  0.85856083  1.          0.        ]
 [ 0.54863056  0.22523717 -0.23970829  1.        ]]
U = 
 [[ 0.83656605  0.92077333  0.75609823  0.94869306]
 [ 0.          0.42620672  0.46568797  0.66536117]
 [ 0.          0.         -0.13965511  0.03045832]
 [ 0.          0.          0.         -0.19739455]]
P*L*U = 
 [[0.28599695 0.6807093  0.51865375 0.92604119]
 [0.10143027 0.53784679 0.55736184 0.78038639]
 [0.83656605 0.92077333 0.75609823 0.94869306]
 [0.4589657  0.60116199 0.55318533 0.46565042]] 



#### Is P orthogonal?

In [51]:
print("inv(P) = \n",linalg.inv(P),"\n")

print("transpose(P) = \n",P.T,"\n")

print("P.T*P = \n",np.matmul(P.T,P),"\n")

inv(P) = 
 [[ 0. -0.  1. -0.]
 [ 0.  1.  0. -0.]
 [ 1.  0.  0. -0.]
 [ 0.  0.  0.  1.]] 

transpose(P) = 
 [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]] 

P.T*P = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 



**Yes!** We see that $P^T = P^{-1}$ and $P^T \cdot P = I$.

#### MATLAB

Defines LU decomposition as follows:

$$ P \cdot A = L \cdot U$$

Consider $$A \cdot x=b$$

Using MATLAB LU definition

$$P\cdot A = L\cdot U$$

$$P^T \cdot P \cdot A = P^T \cdot L \cdot U$$

$$A = P^T \cdot L \cdot U$$

Substitute into linear system:

$$P^T \cdot L \cdot U \cdot x = b$$

$$ L \cdot U \cdot x = P \cdot b$$

Let $y = U \cdot x$ and substitute.

Step 1. Solve $L \cdot y = P \cdot b$ for $y$

Step 2. Solve $U \cdot x = y$ for $x$

In [53]:
# Calculate Pb
Pb = P.dot(b)
print("P*b = \n",Pb,"\n")

# Step 1
yLU = linalg.solve(L,Pb)
print("yLU = \n",yLU,"\n")

# Step 2
xLU = linalg.solve(U,yLU)
print("xLU = \n",xLU,"\n")

P*b = 
 [[0.22804181]
 [0.80236214]
 [0.04938299]
 [0.00301726]] 

yLU = 
 [[ 0.22804181]
 [ 0.77471299]
 [-0.69371592]
 [-0.46287707]] 

xLU = 
 [[ 1.27900016]
 [-7.82933087]
 [ 5.47877321]
 [ 2.3449334 ]] 



#### SciPy

Defines LU decomposition as:

$$ A = P \cdot L \cdot U $$

Consider $$A \cdot x=b$$

SciPy LU definition

$$A = P \cdot L\cdot U$$

Substitute into linear system:

$$P \cdot L \cdot U \cdot x = b$$
$$P^T \cdot P \cdot L \cdot U \cdot x = P^T \cdot b$$
$$L \cdot U \cdot x = P^T \cdot b$$

Let $y = U \cdot x$ and substitute.

Step 1. Solve $L \cdot y = P^T \cdot b$ for $y$

Step 2. Solve $U \cdot x = y$ for $x$

In [55]:
## LU decomposition algorithm.
Pb = (P.T).dot(b)
print("P.T*b = \n",Pb,"\n")

# Step 1
yLU = linalg.solve(L,Pb)
print("yLU = \n",yLU,"\n")

# Step 2
xLU = linalg.solve(U,yLU)
print("xLU = \n",xLU,"\n")

P.T*b = 
 [[0.22804181]
 [0.80236214]
 [0.04938299]
 [0.00301726]] 

yLU = 
 [[ 0.22804181]
 [ 0.77471299]
 [-0.69371592]
 [-0.46287707]] 

xLU = 
 [[ 1.27900016]
 [-7.82933087]
 [ 5.47877321]
 [ 2.3449334 ]] 



**What is the difference?** A transpose.


#### Verify our answer with `linalg.solve`

Solve the linear system using linalg.solve

In [58]:
x = linalg.solve(A,b)
print("x = \n",x)

x = 
 [[ 1.27900016]
 [-7.82933087]
 [ 5.47877321]
 [ 2.3449334 ]]


## Invertable Matrix Theorem
*Linear Algebra and Its Applications* by David C. Lay, 3rd edition

a. $A$ is an invertible matrix.

b. $A$ is row equivalent to the $n \times n$ identity matrix.

c. $A$ has $n$ pivot positions.

d. The equation $Ax = 0$ has only the trivial solution.

e. The columns of $A$ form a linearly independent set.

f. The linear transformation $x\longmapsto Ax$ is one-to-one.

g. The equation $Ax = b$ has at least one solution for each $b$ in $\mathbb{R}^n$.

h. The columns of $A$ span $\mathbb{R}^n$.

i. The linear transformation $x\longmapsto Ax$ maps $\mathbb{R}^n$ onto $\mathbb{R}^n$.

j. There is an $n \times n$ matrix $C$ such that $CA = I$.

k. There is an $n \times n$ matrix $D$ such that $AD = I$.

l. $A^T$ is an invertible matrix.

**Let $A$ be an $n \times n$ matrix. Then the following statements are each equivalent to the statement that $A$ is an invertible matrix.**

m. The columns of $A$ form a basis of $\mathbb{R}^n$.

n. Col$A$ = $\mathbb{R}^n$

o. dim Col$A$ = $N$

p. rank $A$ = $N$

q. Nul$A$ = $\{0\}$

r. dim Nul$A$ = $0$

**Let $A$ be an $n \times n$ matrix. Then $A$ is invertible if and only if:**

s. The number 0 is *not* an eigenvalue of $A$.

t. The determinant of $A$ is *not* zero.

**Let $A$ be an $n \times n$ matrix. Then the following statements are each equivalent to the statement that $A$ is an invertible matrix.**

u. (Col$A$)$^\perp$ = $\{0\}$.

v. (Nul$A$)$^\perp$ = $\mathbb{R}^n$.

w. Row$A$ = $\mathbb{R}^n$.

x. $A$ has $n$ nonzero singular values.

## Eigenvectors and Eigenvalues

Section **2.2 Vectors and Matrices** in Biegler (2010)

### Eigenvalues/Eigenvectors Definition

* For a square matrix $A \in \mathbb{R}^{n\times n}$, the *eigenvalue* $\lambda$ and the corresponding *eigenvector* $v \neq 0$ satisfy $Av = \lambda v$.
* Because $(A-\lambda I)v = 0$, $(A-\lambda I)$ is singular, and we can define a characteristic $n$th degree polynomial given by det$(A-\lambda I)$ = $0$ to find the $n$ eigenvalues.
* det$(A)$ = $\prod_{i=1}^n\lambda_i$.
* Eigenvalues of symmetric matrices are always real. Moreover, by collecting eigenvectors and eigenvalues, a symmetric matrix $A \in \mathbb{R}^{n \times n}$ can be represented by $A = V\wedge V^T$, where $V$ is the orthogonal matrix of eigenvectors, $V = [v_1,v_2,...,v_n]$, and $\wedge$ is a diagonal matrix of eigenvalues with $\{\wedge\}_{ii} = \lambda_i$.
* Nonsymmetric matrices can have complex eigenvalues. Also, eigenvalues are not defined for nonsquare matrices. Instead, *singular values* $\sigma_i \geq 0$, $i = 1,...,m,$ are often useful to characterize $A \in \mathbb{R}^{n \times m}$ with $m \leq n$. These are derived from the eigenvalues of $(A^TA)$ with $\sigma_i = [\lambda_i(A^TA)]^{\frac{1}{2}}$.
* Consider the matrix $A \in \mathbb{R}^{n \times m}$ with all real eigenvalues. Such matrices can be further classified as follows:
    - Matrices with $\lambda_i > 0, i = 1,n,$ are said to be *positive definite*; i.e., $y^TAy > 0$ for all $y \neq 0$.
    - Matrices with $\lambda_i < 0, i = 1,n,$ are said to be *negative definite*; i.e., $y^TAy < 0$ for all $y \neq 0$.
    - Matrices with $\lambda_i \geq 0, i = 1,n,$ are said to be *positive semidefinite*; i.e., $y^TAy \geq 0$ for all $y \neq 0$.
    - Matrices with $\lambda_i \leq 0, i = 1,n,$ are said to be *negative semidefinite*; i.e., $y^TAy \leq 0$ for all $y \neq 0$.
    - Matrices with both positive and negative eigenvalues are *indefinite*.
    - A matrix with $\lambda_i = 0$, for some $i$, is *singular*.

### Practice Activities

In [59]:
# Create matrix for activities
Ae = np.array([(0, -4, -6), (-1, 0, -3), (1, 2, 5)])
print("Ae = \n",Ae)

Ae = 
 [[ 0 -4 -6]
 [-1  0 -3]
 [ 1  2  5]]


<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;">
<b>Home Activity</b>: Do you expect the above matrix to have negative eigenvalues?
</div>

**Choose:** Yes/No/Cannot tell from inspection.

**Justification:**

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Calculate the eigenvalues and corresponding eigenvectors.
</div>

In [61]:
# Calculations
### BEGIN SOLUTION
print("Matrix = \n",Ae,"\n")
l, v = linalg.eig(Ae)
print("Eigenvalues = ",l,"\n")
print("Eigenvectors = \n",v,"\n")
### END SOLUTION

Matrix = 
 [[ 0 -4 -6]
 [-1  0 -3]
 [ 1  2  5]] 

Eigenvalues =  [1.+0.j 2.+0.j 2.+0.j] 

Eigenvectors = 
 [[-0.81649658 -0.0111458   0.90265832]
 [-0.40824829 -0.8302799   0.1523847 ]
 [ 0.40824829  0.5572352  -0.40247591]] 



<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Based on your calculations above, is this matrix i) positive definite, ii) positive semi definite, iii) negative definite, iv) negative semi definite, v) indefinite, or vi) cannot say without additional calculations? Write a sentence to justify your answer.
</div>

**Answer:**

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Calculate the determinate using only the eigenvalues.
    </div>

In [70]:
# Determinate calculation
### BEGIN SOLUTION
det = 1 # initialize
for i in range(len(l)):
    det = det*l[i]
print("Det = ",det)
### END SOLUTION

Det =  (3.9999999999999973+0j)


## Singular Value Decomposition
Refer to [this notebook](../02-publish/03-LU-Factorization.ipynb) for notes on singular value decomposition.

Remember, SVD can be thought of as another type of matrix factorization.  We can represent an $m \times n$ matrix as $A = U\cdot \sum \cdot V^T$.

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Calculate the singular value decomposition of $A_d$ and $B_d$.
    </div>

In [74]:
# Generate matrices
n = 2
m = 3
A_d = np.random.rand(n,m)
B_d = np.random.rand(m,n)
print("A_d = ")
print(A_d)
print("\nB_d = ")
print(B_d)

### BEGIN SOLUTION
U,S,V = linalg.svd(A_1)
print("\nU = \n",U,"\n")
print("S = \n",S,"\n")
print("V = \n",V,"\n")
### END SOLUTION

A_d = 
[[0.20069198 0.09620302 0.37939729]
 [0.26127421 0.17592154 0.35630356]]

B_d = 
[[0.86030731 0.4669534 ]
 [0.36787739 0.26036492]
 [0.01476637 0.72953695]]

U = 
 [[-0.59980845 -0.80014362]
 [-0.80014362  0.59980845]] 

S = 
 [1.59157804 0.45189278] 

V = 
 [[-0.4481125  -0.75389347 -0.48045794]
 [ 0.88974984 -0.42831115 -0.15778081]
 [-0.08683557 -0.49819093  0.86270817]] 



<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: What is the rank of each matrix? (from inspecting singular values?)
    </div>

**Answer:**

## Vector and Matrix Norms

Section **2.2 Vectors and Matrices** in Biegler (2010)
![Book](figures/norm1.png)
![Book](figures/norm2.png)

* A *vector norm* $\parallel x\parallel = 0 \Rightarrow x=0$ for $x \in \mathbb{R}^n$,

In [22]:
x = np.random.rand(3,1)
print("x = \n",x)

y = np.random.rand(3,1)
print("y = \n",y)

x = 
 [[0.02808233]
 [0.20488865]
 [0.77425602]]
y = 
 [[0.73113614]
 [0.20737529]
 [0.97754014]]


**Activity**
* Verify the vector norm properties hold for the p-2 norm using $x$ and $y$. Hint: linalg.norm()
* Calculate $||A_l||_1$, $||A_l||_{\infty}$ and $||A_l||_2$ using both the rules given above and SciPy

## Condition Number

**Activity**
* Estimate the condition number of $A_l$ by inspecting the SVD results.
* Calculate the condition number of $A_l$ using np.linalg.cond()