# Linear Algebra Review and SciPy Basics

Screenshots from Section **2.2 Vectors and Matrices** in Biegler (2010)

**Recommended Links**
* [NumPy Documentation - Main Page](https://docs.scipy.org/doc/numpy-1.15.0/reference/)
* [SciPy Documentation - Main Page](https://docs.scipy.org/doc/scipy-1.1.0/reference/)
* [SciPy Linear Algebra - Tutorial](https://docs.scipy.org/doc/scipy-1.1.0/reference/tutorial/linalg.html)
* [SciPy Linear Algebra - API](https://docs.scipy.org/doc/scipy-1.1.0/reference/linalg.html)
* [SciPy Lecture Notes](http://www.scipy-lectures.org/) (Especially 1.1 - 1.6 for everyone and 2.1 - 2.2 for advanced users)

Tip: We will mostly use SciPy for linear algebra. (It has more sophisticated capabilities than NumPy.) We will use NumPy if/when SciPy does not offer a specific command.

In [3]:
# Load required Python libraries.
import matplotlib.pyplot as plt
import numpy as np
from scipy import linalg

## Notation (for textbook)
* Scalar constants and variables - Greek letters
* Vectors - Lower case Roman letters
* Matrices - Upper case Roman letters

The notation for lectures will (hopefully) be obvious from context. I sometimes use Greek letters for constants and Roman letters for variables... unless the Greek letters have engineering or scientific meaning.


## Matrix Operations

In this section we will introduce properties of matrices with code examples following each property.

The following properties are taken from Section **2.2 Vectors and Matrices** in Biegler (2010).

### Property #1:

Multiplying two matrices $A$ $\in$ $\mathbb{R}^{n \times m}$ and $B$ $\in$ $\mathbb{R}^{m \times p}$ leads to the product $C \in$ $\mathbb{R}^{n \times p}$ with elements $\{C\}_{ij}$ = $\sum_{k=1}^m \{A\}_{ik}\{B\}_{kj}$. This operation is defined only if the number of columns in $A$ and rows of $B$ is the same.

<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;"> 
<b>Home Activity</b>: The code below demonstrates matrix multiplication.  Before running the code below, what is the dimension of A*B?
</div>

In [4]:
# Generate random matrices
n = 2
m = 3

Ao = np.random.rand(n,m)
Bo = np.random.rand(m,n)

print("Ao = ")
print(Ao)
print("\nBo = ")
print(Bo)

# Calculate A*B using Python
print("\nAo*Bo =")
print(Ao.dot(Bo))

Ao = 
[[0.14192588 0.41191867 0.21223085]
 [0.3574524  0.44237956 0.91616785]]

Bo = 
[[0.44219947 0.89121706]
 [0.9567635  0.05714551]
 [0.70864219 0.58671576]]

Ao*Bo =
[[0.60726403 0.27454525]
 [1.23055307 0.8813778 ]]


### Property #2:

The *transpose* of $A$ $\in$ $\mathbb{R}^{n \times m}$ is $A^T$ $\in$ $\mathbb{R}^{m \times n}$ with the rows and columns of A interchanged, i.e.$\{A^T\}_{ij} = \{A\}_{ji}$.

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Calculate $A_o^{T}$</div>

In [49]:
# Transpose
### BEGIN SOLUTION
print("transpose(Ao) = \n",Ao.transpose(),"\n")
### END SOLUTION

transpose(Ao) = 
 [[0.14192588 0.3574524 ]
 [0.41191867 0.44237956]
 [0.21223085 0.91616785]] 



### Property #3:

A *symmetric* matrix $A$ $\in$ $\mathbb{R}^{n \times n}$ satisfies $A = A^T$.

### Property #4:

A *diagonal* matrix $A$ $\in$ $\mathbb{R}^{n \times n}$ has nonzero elements only on the diagonal, i.e., $\{A\}_{ij} = 0, i \neq j$.

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Create a random $3 \times 3$ square matrix and check if it is symmetric by comparing it to its transpose.</div>

In [50]:
# Create Square Matrix and Compare with Transpose
### BEGIN SOLUTION
square = np.random.rand(3,3)
print("Square matrix:\n",square)
squareT = square.transpose()
print("Transpose of square matrix:\n", squareT)
### END SOLUTION

Square matrix:
 [[0.17655789 0.33166731 0.53353642]
 [0.3370124  0.70122644 0.39717663]
 [0.78206427 0.33850383 0.3161977 ]]
Transpose of square matrix:
 [[0.17655789 0.3370124  0.78206427]
 [0.33166731 0.70122644 0.33850383]
 [0.53353642 0.39717663 0.3161977 ]]


### Property #5:

The *identity* matrix $I \in \mathbb{R}^{n \times n}$ is defined as 
$$ \{I\}_{ij}=   \left\{
\begin{array}{ll}
      1 \text{ if } i = j, \\
      0 \text{ otherwise.} \\
\end{array} 
\right.  $$

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Create a 3x3 identity matrix.</div>

In [51]:
# Identity matrix
### BEGIN SOLUTION
print("I = \n",np.identity(3),"\n")
### END SOLUTION

I = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



## Determinant

A *determinant* is a scalar associated to a square matrix, i.e., det($A$) for $A$ $\in$ $\mathbb{R}^{n \times n}$, and can be defined recursively by det($A$) = $\sum_i (-1)^{i+j}\{A\}_{ij}\bar{A}_{ij}$ for any column $j$, or det($A$) = $\sum_j (-1)^{i+j}\{A\}_{ij}\bar{A}_{ij}$ for any row $i$, where $\bar{A}_{ij}$ is the determinant of an ($n$-1)-order matrix with row $i$ and column $j$ removed.

We will now manipulate the following matrices to demonstrate properties for the determinant.

In [52]:
# Generate random matrices
nd = 2

A = np.random.rand(nd,nd)
B = np.random.rand(nd,nd)

print("A = ")
print(A)
print("\nB = ")
print(B)

A = 
[[0.86782127 0.32462305]
 [0.06327566 0.65972386]]

B = 
[[0.50895149 0.84391792]
 [0.55147623 0.40202117]]


The following properties are taken from Section **2.2 Vectors and Matrices** in Biegler (2010).

### Property #1: 

det($AB$) = det($A$)det($B$)

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Calculate the determinante of $AB$ and prove it is equal to the product of the determinants of $A$ and $B$.</div>

In [53]:
# Property 1
### BEGIN SOLUTION
print("det(A*B) = ",linalg.det(A.dot(B)))
print("det(A)*det(B) = ",linalg.det(A)*linalg.det(B))
### END SOLUTION

det(A*B) =  -0.1439520705087479
det(A)*det(B) =  -0.1439520705087479


### Property #2:

det($A$) = det($A^T$)

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Calculate the determinant of $A$ and of $A^T$ and prove they are equal.</div>

In [54]:
# Property 2
### BEGIN SOLUTION
print("det(A) = ", linalg.det(A))
print("det(A^T) = ", linalg.det(A.transpose()))
### END SOLUTION

det(A) =  0.5519816612943368
det(A^T) =  0.5519816612943368


### Property #3:

For an $n \times n$ matrix with scalar $\alpha$, det($\alpha A$) = $\alpha^n$det($A$)

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Calculate the determinant of $\alpha A$ and calculate $\alpha$det($A$) and prove they are equal. Let $\alpha$ = 4.</div>

In [55]:
# Property 3
### BEGIN SOLUTION
alpha = 4
print("det(alpha*A) = ", linalg.det(alpha*A))
print("alpha*det(A) = ", alpha*(linalg.det(A)))
### END SOLUTION

det(alpha*A) =  8.831706580709389
alpha*det(A) =  2.207926645177347


### Property #4:

For an identity matrix $I$, det($I$) = 1.

<div style="background-color: rgba(0,0,255,0.05) ; padding: 10px; border: 1px solid darkblue;"> 
<b>Class Activity</b>: Create a $3 \times 3$ identity matrix and calculate the determinant.</div>

In [56]:
# Property 4
### BEGIN SOLUTION
I = np.identity(3)
print(I)
print("det(I) = ", linalg.det(I))
### END SOLUTION

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
det(I) =  1.0


### Calculating $3 \times 3$ Determinant by Hand

Below is an example from *Linear Algebra and Its Applications* by David C. Lay, 3rd edition that shows how to calculate a determinant by hand.

![DET](figures/det_ex1.png)
![DET](figures/det_ex2.png)

<div style="background-color: rgba(0,255,0,0.05) ; padding: 10px; border: 1px solid darkgreen;"> 
<b>Home Activity</b>: Walk through the following example that calculates a $3 \times 3$ determinant by hand.
</div>

For $ n \geq 2$, the **determinant** of an $n \times n$ matrix $A$ = [$a_{ij}$] is the sum of $n$ terms of the form $\pm a_{1j}$ det$A_{1j}$, with plus and minus signs alternating, where the entries $a_{11},a_{12},...,a_{1n}$ are from the first row of $A$.  In symbols, 

det$A$ = $a_{11}$det$A_{11}-a_{12}$det$A_{12}+...+(-1)^{1+n}a_{1n}$det$A_{1n}$
    
= $\sum_{j=1}^n (-1)^{1+j}a_{1j}\text{det}A_{1j}$

**Example:** Compute the determinate of the matrix $A$ = 
$\begin{bmatrix}
1 & 5 & 0\\
2 & 4 & -1\\
0 & -2 & 0
\end{bmatrix}$

**Solution:** Compute det($A$) = $a_{11}$det$A_{11}-a_{12}$det$A_{12}+a_{13}$det$A_{13}$:

det$A$ = $1\cdot$det$\begin{bmatrix} 4 & -1\\ -2 & 0 \end{bmatrix}$ - $5\cdot$det$\begin{bmatrix} 2 & -1\\ 0 & 0 \end{bmatrix}$ + $0\cdot$det$\begin{bmatrix} 2 & 4\\ 0 & -2 \end{bmatrix}$

$= 1(0-2) - 5(0-0) + 0(-4-0)$ 

$= -2$

## Rank
![Book](figures/rank.png)

**Activity**
* Predict the rank of $A_o^T$, $B_o^T$, $A_d$, $B_d$, $C_d$
* Calculate np.linalg.matrix_rank(). Where you correct?

In [9]:
print("rank(A_o) = ",np.linalg.matrix_rank(Ao),"\n")

# Fill in remainder here.

rank(A_o) =  2 



## Inverse
![Book](figures/inv.png)

**Activity**
1. Calculate the inverse of $A_o$ and verity that $A_o^{-1} A_o = I$
2. Verify that det($A^{-1}$) = 1/det($A$)
3. Is $Q$ an orthogonal matrix?

In [10]:
# Task 1

# Task 2

# Task 3
# Is this an orthogonal matrix? Yes, no, or need more information?
theta = 0.2
Q = np.array([(np.cos(theta), -np.sin(theta)),(np.sin(theta),np.cos(theta))])

print("Q = ")
print(Q)

Q = 
[[ 0.98006658 -0.19866933]
 [ 0.19866933  0.98006658]]


## Solving Linear Systems
Consider the linear system $A_l x = b_l$

In [11]:
Al = np.array([(4,3),(6,3)])
bl = np.array([1,0])
print("Al = \n",Al)
print("\nbl = \n",bl)

Al = 
 [[4 3]
 [6 3]]

bl = 
 [1 0]


### Explicit Inverse

Calculate $x$ by explicitly using $A_l^{-1}$. Hint: Use linalg.inv().

In [12]:
Ainv = linalg.inv(Al)
print("Ainv = \n",Ainv,"\n")

# Now calculate and print x

Ainv = 
 [[-0.5         0.5       ]
 [ 1.         -0.66666667]] 



### LU Decomposition

Perform LU decomposition on $A_l$. What structures do the $P$, $L$, and $U$ matrices have?

In [13]:
# Create test linear systems
A = np.random.rand(4,4)
print("A = \n",A,"\n")

b = np.random.rand(4,1)
print("b = \n",b,"\n")

A = 
 [[0.68331246 0.29422836 0.22419151 0.41620186]
 [0.05988483 0.58705665 0.07246852 0.45441375]
 [0.6024749  0.36997327 0.13872522 0.45388322]
 [0.34311843 0.47101812 0.51826738 0.25525007]] 

b = 
 [[0.00949348]
 [0.82027783]
 [0.90273651]
 [0.37915841]] 



In [14]:
# Perform LU decomposition
(P, L, U) = linalg.lu(A)

# Permutation matrix
print("P = \n",P)

# Lower diagonal matrix
print("L = \n",L)

# Upper diagonal matrix
print("U = \n",U)

# Verify result
print("P*L*U = \n",P.dot(L.dot(U)),"\n")

P = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
L = 
 [[ 1.          0.          0.          0.        ]
 [ 0.08763901  1.          0.          0.        ]
 [ 0.50213986  0.5759686   1.          0.        ]
 [ 0.88169751  0.19696885 -0.18479522  1.        ]]
U = 
 [[ 0.68331246  0.29422836  0.22419151  0.41620186]
 [ 0.          0.56127076  0.05282059  0.41793823]
 [ 0.          0.          0.37526888 -0.19446077]
 [ 0.          0.          0.         -0.03133716]]
P*L*U = 
 [[0.68331246 0.29422836 0.22419151 0.41620186]
 [0.05988483 0.58705665 0.07246852 0.45441375]
 [0.6024749  0.36997327 0.13872522 0.45388322]
 [0.34311843 0.47101812 0.51826738 0.25525007]] 



#### Is P orthogonal?

In [15]:
print("inv(P) = \n",linalg.inv(P),"\n")

print("transpose(P) = \n",P.T,"\n")

print("P.T*P = \n",np.matmul(P.T,P),"\n")

inv(P) = 
 [[ 1. -0. -0.  0.]
 [ 0.  1. -0.  0.]
 [ 0.  0. -0.  1.]
 [ 0.  0.  1.  0.]] 

transpose(P) = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]] 

P.T*P = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 



**Yes!** We see that $P^T = P^{-1}$ and $P^T \cdot P = I$.

#### MATLAB

Defines LU decomposition as follows:

$$ P \cdot A = L \cdot U$$

Consider $$A \cdot x=b$$

Using MATLAB LU definition

$$P\cdot A = L\cdot U$$
$$P^T \cdot P \cdot A = P^T \cdot L \cdot U$$
$$A = P^T \cdot L \cdot U$$

Substitute into linear system:

$$P^T \cdot L \cdot U \cdot x = b$$
$$ L \cdot U \cdot x = P \cdot b$$

Let $y = U \cdot x$ and substitute.

Step 1. Solve $L \cdot y = P \cdot b$ for $y$

Step 2. Solve $U \cdot x = y$ for $x$

In [16]:
Pb = P.dot(b)
print("P*b = ",Pb,"\n")

yLU = linalg.solve(L,Pb)
print("yLU = ",yLU,"\n")

xLU = linalg.solve(U,yLU)
print("xLU = ",xLU,"\n")

P*b =  [[0.00949348]
 [0.82027783]
 [0.37915841]
 [0.90273651]] 

yLU =  [[ 0.00949348]
 [ 0.81944583]
 [-0.09758371]
 [ 0.71492782]] 

xLU =  [[  9.4407442 ]
 [ 19.58501477]
 [-12.08206663]
 [-22.81406129]] 



#### SciPy

Defines LU decomposition as:

$$ A = P \cdot L \cdot U $$

Consider $$A \cdot x=b$$

SciPy LU definition

$$A = P \cdot L\cdot U$$

Substitute into linear system:

$$P \cdot L \cdot U \cdot x = b$$
$$P^T \cdot P \cdot L \cdot U \cdot x = P^T \cdot b$$
$$L \cdot U \cdot x = P^T \cdot b$$

Let $y = U \cdot x$ and substitute.

Step 1. Solve $L \cdot y = P^T \cdot b$ for $y$

Step 2. Solve $U \cdot x = y$ for $x$

In [17]:
## LU decomposition algorithm.
Pb = (P.T).dot(b)
print("P.T*b = ",Pb,"\n")

yLU = linalg.solve(L,Pb)
print("yLU = ",yLU,"\n")

xLU = linalg.solve(U,yLU)
print("xLU = ",xLU,"\n")

P.T*b =  [[0.00949348]
 [0.82027783]
 [0.37915841]
 [0.90273651]] 

yLU =  [[ 0.00949348]
 [ 0.81944583]
 [-0.09758371]
 [ 0.71492782]] 

xLU =  [[  9.4407442 ]
 [ 19.58501477]
 [-12.08206663]
 [-22.81406129]] 



**What is the difference?** A transpose.


#### Verify our answer with `linalg.solve`

Solve the linear system using linalg.solve

In [18]:
x = linalg.solve(Al,bl)
print("x = \n",x)

x = 
 [-0.5  1. ]


## Invertable Matrix Theorem
Screenshots from *Linear Algebra and Its Applications* by David C. Lay, 3rd edition

![IMT](figures/imt1.png)
![IMT](figures/imt2.png)
![IMT](figures/imt3.png)
![IMT](figures/imt4.png)

## Eigenvectors and Eigenvalues
![Book](figures/eig.png)

In [19]:
Ae = np.array([(0, -4, -6), (-1, 0, -3), (1, 2, 5)])
print("Ae = \n",Ae)

Ae = 
 [[ 0 -4 -6]
 [-1  0 -3]
 [ 1  2  5]]


**Activity**
* Do you expect this matrix to have negative eigenvalues? Choose: Yes / No / Cannot tell from inspection.
* Calculate the eigenvalues.
* Based on your calculations above, is this matrix i) positive definite, ii) positive semi definite, iii) negative definite, iv) negative semi definite, v) indefinite, or vi) cannot say without additional calculations? Write a sentence to justify your answer.
* Calculate the determinate using only the eigenvalues.

In [20]:
# Expect negative eigenavalues?
# Yes / No / Cannot tell from inspect?
# Write a sentence to justify your answer.

### Calculate eigenvalues

# Matrix Al
print("Matrix = \n",Al,"\n")
l, v = linalg.eig(Al)
print("Eigenvalues = ",l,"\n")
print("Eigenvectors = \n",v,"\n")

Matrix = 
 [[4 3]
 [6 3]] 

Eigenvalues =  [ 7.77200187+0.j -0.77200187+0.j] 

Eigenvectors = 
 [[ 0.62246561 -0.53222953]
 [ 0.78264715  0.8466001 ]] 



## Singular Value Decomposition
Notes will be given in class.

**Activity**
* Calculate singular value decomposition of $A_l$ and $C_d$
* What is the rank of each matrix?

In [21]:
# Matrix Al
print("Matrix = \n",Al,"\n")
U,s,Vh = linalg.svd(Al)
print("U = \n",U,"\n")
print("S = \n",s,"\n")
print("Vh = \n",Vh,"\n")

## Rank (from inspecting singular values)?

Matrix = 
 [[4 3]
 [6 3]] 

U = 
 [[-0.59581566 -0.80312122]
 [-0.80312122  0.59581566]] 

S = 
 [8.33557912 0.71980602] 

Vh = 
 [[-0.86400595 -0.50348159]
 [ 0.50348159 -0.86400595]] 



## Vector and Matrix Norms
![Book](figures/norm1.png)
![Book](figures/norm2.png)

In [22]:
x = np.random.rand(3,1)
print("x = \n",x)

y = np.random.rand(3,1)
print("y = \n",y)

x = 
 [[0.02808233]
 [0.20488865]
 [0.77425602]]
y = 
 [[0.73113614]
 [0.20737529]
 [0.97754014]]


**Activity**
* Verify the vector norm properties hold for the p-2 norm using $x$ and $y$. Hint: linalg.norm()
* Calculate $||A_l||_1$, $||A_l||_{\infty}$ and $||A_l||_2$ using both the rules given above and SciPy

## Condition Number

**Activity**
* Estimate the condition number of $A_l$ by inspecting the SVD results.
* Calculate the condition number of $A_l$ using np.linalg.cond()